### ISSUE TITLE
"还原“按钮点击后弹窗位置异常

### ISSUE THREAD

**Issue by Teemwu** [Coande/co-trans-ext#3]
### 描述
如图所示，点击”还原“按钮后弹窗并没有回到所选词的位置，而是在右上角，有时候还看不见，很影响体验。
![image](https://user-images.githubusercontent.com/16522288/58558883-7dbe5480-8254-11e9-8055-bdd83dbf3173.png)

### 希望
点击”还原“按钮弹窗能回到选词上。

**Comment by Coande** [comment]
已更新，取消固定时，定位在可视范围内。由于涉及到过渡动画、当前选词可能无法定位等因素，不定位到选词附近。
