### ISSUE TITLE
点击翻译图标弹窗显示后自动关闭

### ISSUE THREAD

**Issue by Teemwu** [Coande/co-trans-ext#4]
### 描述
选词后鼠标移动到翻译图标那，图标动画执行期间点击图标，翻译弹窗显示立即又关闭了。

**Comment by Coande** [comment]
不能复现，需要什么条件吗？

**Comment by Teemwu** [comment]
经分析发现，是点下去瞬间，动画刚好执行完，翻译按钮消失，点到了空白的地方，弹窗就自动关闭了。

**Comment by Coande** [comment]
噢，pull requests 后导致的问题，因为定位方式改变了。
